version: "3"

services:
  redis:
    container_name: "redis"
    image: "redis:alpine"
    restart: always
    command: redis-server --appendonly yes --replica-read-only no
    ports:
      - "6379:6379"
    volumes:
      - ".data/redis:/data"

  postgres:
    image: "postgres:14"
    restart: always
    container_name: "pg"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: izing
    volumes:
      - ".data/pg:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: "rabbitmq"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - .data/rabbitmq/data/:/var/lib/rabbitmq/
      - .data/rabbitmq/logs/:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
